name: topk

channels:
  - default
  - conda-forge

dependencies:
  - python=3.9.7
  - seaborn=0.11.2
  - altair=4.2.0
  - numpy=1.23.1
  - matplotlib=3.5.2
  - SPARQLWrapper=1.8.5
  - click=8.1.3
  - pandas=1.4.3
  - tqdm=4.64.0
  - setuptools=63.1.0
  - pyyaml=6.0
  - pyparsing=2.4.7
  - rdflib=5.0.0
  - protobuf=3.15.7
  - notebook=6.4.12
  - pip
  - pip:
    - pybind11==2.2.4
    - hdt==2.3
    - snakemake==7.8.5