name: SaGe experimental server
quota: 75
max_results: 10000
stateless: False
filter_push_down: True
values_push_down: True
graphs:
-
  name: watdiv10M
  uri: http://example.com/datasets/watdiv10M
  backend: hdt-file
  file: ../datasets/watdiv10M.hdt