name: SaGe experimental server
quota: 75
max_results: 10000
max_limit: 10000
stateless: True
graphs:
-
  name: watdiv10M
  uri: http://example.com/datasets/watdiv10M
  backend: hdt-file
  file: ../datasets/watdiv10M.hdt
-
  name: wikidata2017
  uri: http://example.com/datasets/wikidata2017
  backend: hdt-file
  file: ../datasets/wikidata2017.hdt